//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DsiCodetech.Administrador.Repository.PosAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_articulos_principales
    {
        public string cod_principal { get; set; }
        public string cod_anexo { get; set; }
        public string cod_interno { get; set; }
        public string desc_principal { get; set; }
        public string desc_anexo { get; set; }
        public string unidad_principal { get; set; }
        public string unidad_anexo { get; set; }
        public decimal cantidad_ump { get; set; }
        public decimal cantidad_uma { get; set; }
        public System.Guid id_proveedor { get; set; }
        public decimal precio_compra { get; set; }
        public decimal precio_compra_anexo { get; set; }
    }
}
