//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DsiCodetech.Administrador.Repository.PosAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_clasificacion
    {
        public long id_dpto { get; set; }
        public string departamento { get; set; }
        public long id_cat { get; set; }
        public string categoria { get; set; }
        public long id_subcat { get; set; }
        public string subcategoria { get; set; }
        public long id_linea { get; set; }
        public string linea { get; set; }
    }
}
