//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DsiCodetech.Administrador.Repository.PosAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_items
    {
        public string cod_barras { get; set; }
        public string Expr1 { get; set; }
        public string descripcion { get; set; }
        public decimal precio_venta { get; set; }
        public System.DateTime fecha_registro { get; set; }
    }
}
