//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DsiCodetech.Administrador.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class colector_inventario_fisico
    {
        public System.Guid id_inventario_fisico { get; set; }
        public System.Guid id_proveedor { get; set; }
        public string user_name { get; set; }
        public System.DateTime fecha_ini { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public System.DateTime fecha_registro { get; set; }
    }
}
