//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DsiCodetech.Administrador.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class colector_usuario
    {
        public string user_name { get; set; }
        public string password { get; set; }
        public string tipo_usuario { get; set; }
        public bool enable { get; set; }
        public System.DateTime fecha_registro { get; set; }
    }
}
