//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DsiCodetech.Administrador.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Db_cfdi_facturas_entidades : DbContext
    {
        public Db_cfdi_facturas_entidades()
            : base("name=Db_cfdi_facturas_entidades")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<clave_producto_serv> clave_producto_serv { get; set; }
        public virtual DbSet<exportacion> exportacion { get; set; }
        public virtual DbSet<forma_pago> forma_pago { get; set; }
        public virtual DbSet<mes> mes { get; set; }
        public virtual DbSet<metodo_pago> metodo_pago { get; set; }
        public virtual DbSet<moneda> moneda { get; set; }
        public virtual DbSet<pais> pais { get; set; }
        public virtual DbSet<periodicidad> periodicidad { get; set; }
        public virtual DbSet<regimen_fiscal> regimen_fiscal { get; set; }
        public virtual DbSet<tipo_comprobante> tipo_comprobante { get; set; }
        public virtual DbSet<tipo_relacion> tipo_relacion { get; set; }
        public virtual DbSet<uso_cfdi> uso_cfdi { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
    }
}
