//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DsiCodetech.Administrador.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public factura()
        {
            this.factura_articulo = new HashSet<factura_articulo>();
            this.factura_venta = new HashSet<factura_venta>();
            this.metodo_pago = new HashSet<metodo_pago>();
        }
    
        public long id_factura { get; set; }
        public System.DateTime fecha_remision { get; set; }
        public System.Guid id_cliente { get; set; }
        public string cfdi_relacionado { get; set; }
        public string uuid_relacionado { get; set; }
        public string id_comprobante { get; set; }
        public string id_condicion { get; set; }
        public string id_uso { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual comprobante comprobante { get; set; }
        public virtual condicion_pago condicion_pago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura_articulo> factura_articulo { get; set; }
        public virtual uso_cfdi uso_cfdi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura_venta> factura_venta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<metodo_pago> metodo_pago { get; set; }
    }
}
